Update GitconnectorApplication.java
prasad-glx/gitconnector pull request #7
Opened 2020-09-24 09:02 UTC by Anusha-cell

I made some changes

2020-09-24 09:04 UTC, prasadglx requested changes
please clean the code

2020-09-24 09:09 UTC, Anusha-cell commented
Code cleanup completed

2020-09-24 09:10 UTC, prasadglx approved these changes
Request got approved

2020-09-24 09:10 UTC, merged

2020-09-25 06:01 UTC, prasadglx commented
Merged the PR